### PR TITLE
RUB-5 Create 'Item' model

### PR DESCRIPTION
**Pull request by webandriy**
Add model 'Item' (app/models/item.rb), migration (db/migrate/20170925210817_create_items.rb) and item_spec.rb (spec/models/item_spec.rb).

### CODE REVIEW

**Comment by rokor** [comment]
@webandriy Add 2 more members to review and update header of the ticket. Also, add description.

**Comment by webandriy** [comment]
what exactly i need to write in header of the ticket and in description? 😐

**Comment by rokor** [comment]
@webandriy header should include Jira ticket `Rub - {id} : ....`. Description obviously should contain changes that you did.

**Comment by webandriy** [comment]
done it!

**Review by rokor — APPROVED** [review]

**Comment by rokor** [comment]
👍

**Review by sonishc — APPROVED** [review]

**Review by mayar2610 — APPROVED** [review]

**Pull request merged**
